### PR TITLE
arm osx migration

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Fix #7

**Comment by Tobias-Fischer** [comment]
@xorg-libxrandr this is ready to be merged. Thanks!

**Review by pkgw — CHANGES_REQUESTED** [review]
Thanks once again for helping out the migrator! Here too I'd like to ask that you make the same kind of change as in conda-forge/xorg-libxtst-feedstock#8. Then we should be good to go.

**Comment by Tobias-Fischer** [comment]
Thanks for the review @pkgw - it should be ready to go now.

**Review by pkgw — APPROVED** [review]
Thanks!

**Pull request merged**
